# Generated by Django 4.0.3 on 2023-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_technician_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Canceled', 'Canceled'), ('Finished', 'Finished')], default='Created', max_length=25),
        ),
    ]
