# Generated by Django 4.0.3 on 2023-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vin',
            field=models.CharField(default='dnfd98', max_length=17),
            preserve_default=False,
        ),
    ]
